services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: gads
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: gads
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker_psql_seed:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gads"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
    driver: local
