services:
  gads:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gads
    ports:
      - "3000:3000"
    environment:
      GADS_HOSTNAME: localhost
      GADS_USERNAME: test@example.com
      GADS_PASSWORD: xyz123
      PSQL_USER: gads_user
      PSQL_PASSWORD: gads_pass
      PSQL_DB: gads_db
      PSQL_HOSTNAME: db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    container_name: gads_db
    environment:
      POSTGRES_USER: gads_user
      POSTGRES_PASSWORD: gads_pass
      POSTGRES_DB: gads_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gads_user -d gads_db -h db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: